[package]
name = "tauri-file-server"
version = "0.1.0"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.0", features = [] }

[dependencies]
tauri = { version = "2.0", features = [] }
tauri-plugin-opener = "2"
tokio = { version = "1", features = ["full"] }
axum = { version = "0.7", features = ["multipart"] }
local-ip-address = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
tower-http = { version = "0.5", features = ["cors", "fs"] }
regex = "1.10"
urlencoding = "2"
tokio-util = { version = "0.7", features = ["io"] }
futures-util = "0.3"
